service: kamal

image: 	chrome-insight-471112-g2/gcr.io/kamal

servers:
  web:
    - 34.41.103.180

builder:
  arch: amd64

proxy:
  app_port: 3000
  # host: 35.193.245.114
  healthcheck:
    path: /
    interval: 10
    timeout: 35

registry:
  server: us-docker.pkg.dev
  username: _json_key_base64
  password:
    - KAMAL_REGISTRY_PASSWORD
ssh:
  user: petruneactabita
  keys: []
  port: 22

env:
  clear:
    PORT: 3000

